using AtlantidaApplicationAPI.Models;

namespace AtlantidaApplicationAPI.Interfaces
{
    public interface IService_TIPOTRANSACCION
    {
        Task<List<TIPOTRANSACCION>> TIPOTRANSACCION_SELECT(TIPOTRANSACCION model);
        Task<List<TIPOTRANSACCION>> TIPOTRANSACCION_INSERT(TIPOTRANSACCION model);
        Task<List<TIPOTRANSACCION>> TIPOTRANSACCION_UPDATE(TIPOTRANSACCION model);
        Task<List<TIPOTRANSACCION>> TIPOTRANSACCION_DELETE(TIPOTRANSACCION model);
    }
}
